// User Endpoints
###
POST http://localhost:8000/users/register
content-type: application/json

{
    "name": "Vivek Joshi",
    "emailId": "vivek.joshi117@sjsu.edu",
    "password": "password"
}


###
GET http://localhost:5000/users/vivek.joshi17@sjsu.edu
# content-type: application/json

# {
   
#     "emailId": "vivek.joshi2@sjsu.edu"
# }


###
POST  http://localhost:8000/users/login
content-type: application/json

{
   
    "emailId": "vivek.joshi17@sjsu.edu",
    "password": "password",
    "ipAddress": ""
}


###
POST http://localhost:8000/users/registerCamera/63e08cd02e597b0ed6ce32be
content-type: application/json

{
    "ip" : "rtsp://admin:admin295@98.35.205.100:554/h264Preview_01_sub",
    "name": "testingRTSP",
    "session" : "sessiontesting2",
    "connection": "connectiontesting2",
    "token": "tokentesting2",
    "isRTSP": true
}


# ssh -i "295-backend.pem" ubuntu@ec2-54-190-19-109.us-west-2.compute.amazonaws.comls

###
POST http://54.190.19.109:8080/users/registerCamera/63e08cd02e597b0ed6ce32be
content-type: application/json

{
    "ip" : "rtsp://admin:admin295@98.35.205.100:554/h264Preview_01_sub",
    "name": "testingRTSP",
    "session" : "sessiontesting2",
    "connection": "connectiontesting2",
    "token": "tokentesting2",
    "isRTSP": true
}


# On EC2 instance
###
POST http://54.190.19.109:8080/users/registerCamera/63e08cd02e597b0ed6ce32be
content-type: application/json

{
    "ip" : "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4",
    "name": "testingRTSP",
    "session" : "sessiontesting2",
    "connection": "connectiontesting2",
    "token": "tokentesting2",
    "isRTSP": true
}

###
POST http://localhost:8000/users/registerCamera/63e08cd02e597b0ed6ce32be
content-type: application/json

{
    "ip" : "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4",
    "name": "testingRTSP",
    "session" : "sessiontesting2",
    "connection": "connectiontesting2",
    "token": "tokentesting2",
    "isRTSP": true
}


# TO refresh the IP cameras
###
PUT http://localhost:8000/users/registerCamera/63e08cd02e597b0ed6ce32be?action=refresh
content-type: application/json

{
    "_id": "64178c9a31e127c75db4404a",
    "ip" : "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4",
    "name": "testingRTSP",
    "port": 50000,
    "isRTSP": true
}

# TO stop the IP cameras
###
PUT http://localhost:8000/users/registerCamera/63e08cd02e597b0ed6ce32be?action=stop
content-type: application/json

{
    "_id": "64178c9a31e127c75db4404a",
    "ip" : "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4",
    "name": "testingRTSP1",
    "port": 50001,
    "isRTSP": true
}




###
DELETE  http://localhost:8000/users/deleteCamera/vivek.joshi17@sjsu.edu/6417f1760d68acd4c8c663c3




###
PUT   http://localhost:8000/users/updateCamera/admin@1234
content-type: application/json

{
    "_id" : "64391fd564b194356219b005",
    "ip" : "rtsp://testing3",
    "name": "Vivek Joshi3"
}

###
GET   http://localhost:8000/users/liveFeed/vivek.joshi17@sjsu.edu


###
GET   http://localhost:8000/users/recordings/63e588d81a45d5ed13627138

###
GET   http://localhost:8000/users/recordings/63e588d81a45d5ed13627138?name=