// User Endpoints
###
POST http://localhost:5000/users/register
content-type: application/json

{
    "name": "Vivek Joshi",
    "emailId": "vivek.joshi17@sjsu.edu",
    "password": "password"
}


###
GET http://localhost:5000/users/vivek.joshi17@sjsu.edu
# content-type: application/json

# {
   
#     "emailId": "vivek.joshi2@sjsu.edu"
# }


###
POST  http://localhost:5000/users/login
content-type: application/json

{
   
    "emailId": "vivek.joshi17@sjsu.edu",
    "password": "password"
}


###
POST http://localhost:8000/users/registerCamera/63e08cd02e597b0ed6ce32be
content-type: application/json

{
    "ip" : "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4",
    "name": "testingRTSP",
    "session" : "sessiontesting2",
    "connection": "connectiontesting2",
    "token": "tokentesting2",
    "isRTSP": "true"
}


###
DELETE  http://localhost:8000/users/deleteCamera/vivek.joshi17@sjsu.edu/6417f1760d68acd4c8c663c3




###
PUT   http://localhost:5000/users/updateCamera/vivek.joshi17@sjsu.edu
content-type: application/json

{
    "_id" : "63e0905b3aba378267b43e68",
    "ip" : "rtsp://testing3",
    "name": "Vivek Joshi3"
}

###
GET   http://localhost:8000/users/liveFeed/vivek.joshi17@sjsu.edu


###
GET   http://localhost:8000/users/recordings/63e588d81a45d5ed13627138

###
GET   http://localhost:8000/users/recordings/63e588d81a45d5ed13627138?name=